spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  web:
    resources:
      static-locations: classpath:/
      add-mappings: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/token_demo?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
  tomcat:
    max-connections: 30000
jwt:
  key: zdWIiOiLmtYvor5XotKblj7ciLCJleHAiOjE2OTc5MDg1NjZ9
  ttl: 10800000

